openapi: 3.1.0
info:
  title: Participant Portal API
  description: Participant Portal API
  version: 1.0.0
servers:
  - url: /participant-portal/api/v1

tags:
  - name: Authorization
    description: |
      Login endpoints to authorize the user.
  - name: Configuration
    description: |
      Accessing data like study configurations, observation data and schedules

security:
  - apiKey: [ ]

paths:
  /login/{more-study-id}/{more-user-data-reference}:
    post:
      operationId: participantLogin
      description: Login the participant with the login code
      tags:
        - Authorization
      security: [ ]
      parameters:
        - $ref: '#/components/parameters/StudyId'
        - $ref: '#/components/parameters/UserDataReference'
        - $ref: '#/components/parameters/LoginCode'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'BaseComponents.yaml#/components/schemas/ApiKey'
        '401':
          description: 'Unauthorized'

  /consent:
    get:
      operationId: retrieveConsentData
      description: Query study information to create consent
      tags:
        - Authorization
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: 'BaseComponents.yaml#/components/responses/StudyInfoResponse'
          description: OK
        '208':
          description: 'Consent was already accepted'
        '403':
          description: 'Forbidden'

    post:
      operationId: acceptConsent
      description: Sends the accepted user consent and returns with a redirect
      tags:
        - Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'BaseComponents.yaml#/components/schemas/StudyConsent'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'BaseComponents.yaml#/components/schemas/Observation'
        '208':
          description: 'Consent was already accepted'
        '403':
          description: 'Forbidden'

  /config/study:
    get:
      operationId: getStudyConfiguration
      description: Loads study-, observation and schedule information
      tags:
        - Configuration
      responses:
        '200':
          $ref: 'BaseComponents.yaml#/components/responses/StudyInfoResponse'
        '403':
          description: 'Forbidden'

components:
  parameters:
    LoginCode:
      name: more-login-code
      in: header
      required: true
      schema:
        type: string
      description: The login token, hashed with sha256 and encrypted in base64
    StudyId:
      name: more-study-id
      in: path
      description: The unique identifier of the study
      required: true
      schema:
        type: string
    UserDataReference:
      name: more-user-data-reference
      in: path
      description: A unique identifier for an action or dataquey
      schema:
        type: string
      required: true

  securitySchemes:
    apiKey:
      description: |
        Login with `apiId` as username and `apiKey` as password
      type: http
      scheme: basic